### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Umasterov** [lennart-rth/Live-Earth-Wallpapers#31]
Windows Defender discovered a Trojan in Liewa\app.exe
Report
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fSabsik.TE.A!ml&threatid=2147780197

**Comment by lennart-rth** [comment]
Oh no! I apologize for that!
As I'm not an expert with the Windows OS, I have no proper explanation for that.
It might be, because Liewa (the name of the app), automatically sets up a task for the Task-Scheduler and the Windows-Defender is classifying that as setting up a trojan. The task, that is set up is used to call the Software every 1h to update the background. Basically, it downloads Images from the internet and sets them as the background. Because this is a process where data is downloaded and processed on the local machine, without the need for the User to confirm the Action. This could mistakenly be identified as a possible threat.
But again I'm not sure why you got this.
